export const sagaColumnActions = {
  GET_COLUMNS_SAGA: 'GET_COLUMNS_SAGA',
  CREATE_COLUMN_SAGA: 'CREATE_COLUMN_SAGA',
  EDIT_COLUMN_SAGA: 'EDIT_COLUMN_SAGA',
  DELETE_COLUMN_SAGA: 'DELETE_COLUMN_SAGA',
};
