export const sagaCommentActions = {
  GET_COMMENTS_SAGA: 'GET_COMMENTS_SAGA',
  CREATE_COMMENT_SAGA: 'CREATE_COMMENT_SAGA',
  EDIT_COMMENT_SAGA: 'EDIT_COMMENT_SAGA',
  DELETE_COMMENT_SAGA: 'DELETE_COMMENT_SAGA',
};
